catppuccin/nix

- default.nix
- flake.lock
- flake.nix
continuation of #1, this just adds flake-compat support
sidenote: `{ self }` was removed due to nix pushing `flake-compat` to
the arguments of `output` (which wouldn't work without the `...` syntax)
and it not being used anyways.
> add flake-compat support

- modules/home-manager/default.nix
- modules/home-manager/kitty.nix
this adds support for the [kitty](https://github.com/catppuccin/kitty) theme
i was also thinking of maybe making a utils file like my previous prs, but with general functions others might need to use (like with `mkUpper` in this case since it's also used by the gtk hm module). let me know what you think :)
> add support for kitty

- .github/workflows/ci.yml
- flake.lock
- flake.nix
- modules/home-manager/bat.nix
- modules/home-manager/default.nix
- modules/nixos/default.nix
as the title says, this vendors nixpkgs, fixing possible issues for those using outdated revisions. with this change, the formatter can also now be set in a flake attribute and `nix fmt` can be used.
i also fixed a bug in the module for bat, which blocked hm activation packages from building due to the command we set now being a default :)
> vendor nixpkgs, cleanup some stuff

- modules/home-manager/gtk.nix
the dark/light suffix is now lowercase as of https://github.com/catppuccin/gtk/releases/tag/v0.6.1
> chore(home-manager): adopt new naming scheme for gtk theme

- modules/home-manager/alacritty.nix
- modules/home-manager/bat.nix
- modules/home-manager/bottom.nix
- modules/home-manager/btop.nix
- modules/home-manager/default.nix
- modules/home-manager/gtk.nix
- modules/home-manager/helix.nix
- modules/home-manager/kitty.nix
- modules/home-manager/lazygit.nix
- modules/home-manager/neovim.nix
- modules/home-manager/polybar.nix
- modules/home-manager/starship.nix
- modules/home-manager/sway.nix
- modules/home-manager/tmux.nix
- modules/lib/default.nix
- modules/lib/mkExtLib.nix
- modules/nixos/grub.nix
this is a redo of (part of) https://github.com/Stonks3141/ctp-nix/pull/1. i'm trying to find a better middle ground here, as `with` has gotten pretty annoying (especially when we use it three times in a row) and i feel has had the opposite effect on readability than intended. it is also a bit of [anti-pattern](https://nix.dev/recipes/best-practices#with-scopes). 
this _doesn't_ use `let inherit ..; in` nearly as much, but does at times when a certain attribute - `lib.ctp` for example - are used twice or more. in other circumstances, attributes are explicitly brought into scope to try to make where they're coming from much more obvious and reduce unnecessary `inherits`. finally, `lib/default.nix` has also seen some work to avoid the weirdness of `rec`, another …
> refactor: use alternatives to `with` and `rec`

- .github/workflows/update-docs.yml
- docs/home-manager-options.md
- docs/nixos-options.md
- flake.nix
this uses `nixosOptionDoc` to automatically create options from our modules. currently, this outputs as commonmark - which i think is ok for now - but this could be expanded to something such as a website with `mkDocs` if preferred
[home-manager options rendered](https://github.com/Stonks3141/ctp-nix/blob/a787926876bf932f7d1f839676ec8f7e02bc5dab/docs/home-manager-options.md)
[nixos options rendered](https://github.com/Stonks3141/ctp-nix/blob/a787926876bf932f7d1f839676ec8f7e02bc5dab/docs/nixos-options.md)
> add autogenerated docs

- modules/home-manager/default.nix
- modules/home-manager/glamour.nix
Adds support for [glamour](https://github.com/charmbracelet/glamour), a Markdown rendering library used in a variety of Go CLIs (including `gh` and `glow`).
> feat(modules/home-manager): add glamour

- modules/home-manager/btop.nix
This fixes the btop module not working due to btop expecting that `color_theme` is set to just the theme file's name, not its entire path.
> fix(home-manager): correctly set btop's theme

- modules/home-manager/default.nix
- modules/home-manager/mako.nix
- modules/lib/default.nix
Adds support for mako. Resolves #16.
I also took the liberty of adding a helper function, `fromINI`, to `lib`.
> feat(home-manager): init mako module

- _sources/generated.json
- _sources/generated.nix
- modules/home-manager/default.nix
- modules/home-manager/hyprland.nix
- nvfetcher.toml
- test.nix
Adds support for Hyprland.
Rather than just adding a `source` statement for the theme, I had to resort to parsing the theme and individually adding the variables to `wayland.windowManager.hyprland.settings` due to quirks in how nix and the hyprland home-manager module work. 
Unfortunately, I doubt these quirks are going to be fixed any time soon: https://github.com/nix-community/home-manager/pull/4263/files#r1271640239
> feat(home-manager): init hyprland module

- modules/home-manager/btop.nix
- modules/home-manager/fish.nix
- modules/home-manager/micro.nix
- modules/lib/default.nix
- test.nix
I don't think it's nice to enable options like these for the user. Instead we should just tell them to do it in their config.
> refactor(home-manager): ensure xdg.enable using assertion

- _sources/generated.json
- _sources/generated.nix
- modules/nixos/console.nix
- nvfetcher.toml
- test.nix
Add module for theming the tty. Resolves #12.
It uses the colors from [catppuccin/tty](https://github.com/catppuccin/tty), but I had to bring in [catppuccin/palette](https://github.com/catppuccin/palette) and parse `palette.json`. Also they appear to have gotten rid of the separate `palette-porcelain.json` file.
> feat(nixos): init console module

- modules/home-manager/lazygit.nix
use `themes-mergable` folder to apply lazygit theme as this has `gui` field
see https://github.com/catppuccin/lazygit/issues/13
> fix: apply lazygit theme

- modules/home-manager/fzf.nix
- test.nix
Adds support for fzf.
I took the same approach that the console module uses and used the palette to manually add the colors from [catppuccin/fzf](https://github.com/catppuccin/fzf).
> feat(home-manager): init fzf module

- modules/home-manager/gtk.nix
Resolves #105 by renaming the gtk cursorTheme
> fix(home-manager): gtk cursor activation

- _sources/generated.json
- _sources/generated.nix
- modules/home-manager/cava.nix
- modules/lib/default.nix
- nvfetcher.toml
- test.nix
Adds support for cava.
I went ahead with duplicating the code for raw parsing the ini file (by using the `-r` parameter for `jc`) as `cava` requires the quotation marks for recognizing hexadecimal color strings.
> feat(home-manager): add support for cava

- modules/home-manager/yazi.nix
> fix(home-manager): add file for yazi syntax highlighting

- _sources/generated.json
- _sources/generated.nix
- modules/home-manager/foot.nix
- nvfetcher.toml
- test.nix
Adds support for foot.
Closes #14 .
PS: `lib.ctp.fromINI` includes comments in variable values. Not a problem here, but might be somewhere else in the future.
> feat(home-manager): add support for foot

- modules/home-manager/gtk.nix
Adds links go GTK 4.0 files as suggested in the [catppuccin/gtk](https://github.com/catppuccin/gtk) README. Closes #107.
> fix(home-manager): link GTK 4.0 files

- modules/home-manager/rofi.nix
Fix for #122.
Alters `programs.rofi.theme` to use an attrset instead of a path directly, so that users can add overriding styles to `programs.rofi.theme`.
A minimal example of how to change the font used in the theme would look like the following:
```nix
{
programs.rofi = {
enable = true;
catppuccin.enable = true;
theme."*".font = "monospace 14";
}
```
I've tested the changes with my NixOS/home-manager configuration, and it seems to work fine.
> fix(home-manager): allow overriding styles for the rofi theme

- modules/home-manager/gtk.nix
- modules/lib/default.nix
This is a bit hacky solution, but I can build my system with `gtk.catppuccin.cursor.accent = "dark"` now.
Feel free to correct my comments, I feel they are grammatically wrong, but don't know how to write better.
> feat(home-manager): allow `dark` and `light` accents for gtk cursors

- dev/flake.lock
- dev/flake.nix
- modules/home-manager/globals.nix
- modules/lib/default.nix
- modules/nixos/globals.nix
- test.nix
This PR:
- Add a new `enable` option to enable `catppuccin` everywhere it can
- Should fix https://github.com/catppuccin/nix/issues/115
I won't be able to test this until late tonight, help needed!
> feat: add `enable` option globally

- modules/home-manager/zellij.nix
- test.nix
Catppuccin is included in zellij and can be enabled as the [official source](https://github.com/catppuccin/zellij?tab=readme-ov-file#usage) instructs.
> feat(home-manager): add support for zellij

- modules/home-manager/k9s.nix
Adds option `transparent` to use the transparent version of the variants. By default, the non-transparent variants override the background colors.
> feat(home-manager): add transparent option for k9s

- _sources/generated.json
- _sources/generated.nix
- nvfetcher.toml
The gtk home-manager module uses catppuccin-gtk packaged in nixpkgs. This source is not used.
> chore(sources/gtk): remove dangling source

- .github/workflows/ci.yml
- .github/workflows/update-docs.yml
- .github/workflows/validate-sources.yml
- dev/flake.nix
- dev/option-doc.nix
- test.nix
- **chore(modules): factor out option doc generation**
- **ci: only validate sources on pushes to main**
> chore(modules): factor out option doc generation

- _sources/generated.json
- _sources/generated.nix
- modules/home-manager/waybar.nix
- nvfetcher.toml
- test.nix
This currently only works if style is defined inline and not a separate css file.
Closes #126
> feat(home-manager): add support for waybar

- modules/home-manager/gtk.nix
I tried to use Latte flavour, but all window titles are black. The reason of that I think is here: https://github.com/catppuccin/gtk/issues/100, so we need to use `dark` and `light` instead of `Dark` and `Light` in style.
current style:
fixed style:
> fix: make dark/light lowecase for style names in gtk

- modules/home-manager/hyprland.nix
Since Home Manager defbb9c, Hyprland on Home Manager now sources files before most other configuration, meaning ctp-nix can now source a theme colors file instead of inserting them into the main configuration. In addition, accent and accentAlpha color variables have been added in a second sourced file.
> feat(home-manager/hyprland): source theme + accent

- modules/home-manager/gtk.nix
The uncapitalized gtkTheme made the generated theme name incorrect wich prevented the theme to be set correctly and made the symlinks in ~/.config/gtk-4.0 broken
> fix(home-manager/gtk): capitalize gtkTheme

- modules/nixos/globals.nix
Literally just a copy-paste from the home-manager module
Currently it does nothing, added for consistency
Closes #134
> feat(modules/nixos): add global `accent` option

- modules/home-manager/fcitx5.nix
The current implementation overrides the configuration for fcitx5 classical ui. This prevents users from changing different ui settings apart from the theme. This adds the ability to optionally install the theme without applying.
> feat(home-manager/fcitx5): add apply option

- .github/workflows/ci.yml
- README.md
- dev/flake.lock
- dev/flake.nix
- modules/home-manager/tofi.nix
- modules/lib/default.nix
- modules/nixos/sddm.nix
fixes #155
fixes #154
thanks to @vdbe for introducing me to `mkSinkUndeclaredOptions` and being the inspiration for `mkVersionedOpts` [here](https://github.com/catppuccin/nix/issues/155#issuecomment-2084507707)
> feat(modules): support nixos & home-manager's stable branches

- .github/workflows/ci.yml
- dev/flake.nix
> ci: don't use graphql to commit

- modules/lib/default.nix
- modules/nixos/sddm.nix
Never use attrset merge operator with `mk*` attrsets since the right hand attrset overrides the left
Fixes #192
> fix(nixos): sddm package not being installed 

- .sources/sources.json
- modules/home-manager/cava.nix
This PR adds a new option to the `programs.cava.catppuccin` module, called `transparent`. Similarly to the `programs.k9s.catppuccin.transparent`, it is a boolean used to select the flavor variant with a transparent background.
This new feature has been added in this PR: https://github.com/catppuccin/cava/pull/11, the source for `cava` therefore needs to be updated.
This should not be a breaking change, as the option defaults to `false`, which will in turn use the same theme file as currently.
**Note**: this PR is still in draft until the aforementioned PR in the source repo is merged, at which time the second commit will be updated to track catppuccin/cava.
> feat(home-manager/cava): add support for themes with transparent background

- .github/workflows/release.yml
I confirmed that it shouldn't break anything
from looking at the documentation, but who
knows with release-please /shrug
> ci(release-please): use action from googleapis

- modules/nixos/sddm.nix
- test.nix
This resolves the error where the theme doesn't work if plasma6 isn't enabled. by default the packge is qt5 sddm, but catppuccin/sddm uses qt6.
> fix(nixos/sddm): use the kde sddm package

- modules/home-manager/gtk.nix
The theme name does not correctly match the one from catppuccin-gtk which should be `catppuccin-${FLAVOR}-${ACCENT}-${SIZE}+${TWEAKS}` as the [Usage docs](https://github.com/catppuccin/gtk/blob/23b52b5b9cde1e11c07315e79a55804d2ac77e3a/docs/USAGE.md#manual-installation) specify.
- Name is all lower case now
- Order changed from `flavor-size-accent-gtkTheme` to `flavor-accent-size+tweaks`
> fix(home-manager): use correct theme name

- modules/home-manager/kvantum.nix
while having `qt.enable` be a prerequisite for this option applying
makes sense, the requirement on a specific `style.name` is not. this
make it more clear by moving that check to an assertion rather than an
internal comparison
> fix(home-manager): assert `qt.style.name` for kvantum theme

- .github/workflows/backport.yml
as we gear up for 1.0.0, this will help us easily backport fixes from `main` to our (eventual) 1.x branch
> ci: add backport action

- modules/home-manager/gtk.nix
Seeing as this does not exist and should be default we should remove the "normal" and replace it with default
> fix(home-manager/gtk): replace `normal` tweak with `default`

- modules/home-manager/gtk.nix
Reverts catppuccin/nix#261
as we said we would do here too https://github.com/catppuccin/nix/pull/270
> Revert "fix(home-manager/gtk): replace `normal` tweak with `default`"

- .sources/sources.json
- modules/home-manager/all-modules.nix
- modules/home-manager/fuzzel.nix
- tests/darwin.nix
- tests/home.nix
> feat(home-manager): add support for fuzzel

- modules/home-manager/zathura.nix
Uses zathura's `include` command to include the theme rather than importing the theme file into nix.
> fix(home-manager/zathura): avoid IFD

- modules/home-manager/foot.nix
Use foot's `include` option to import the theme rather than importing the theme into nix.
> fix(home-manager/foot): avoid IFD

- modules/home-manager/tofi.nix
Use tofi's include option to import the theme rather than importing it into nix.
> fix(home-manager/tofi): avoid IFD

- .sources/sources.json
- modules/home-manager/mpv.nix
Use mpv's `include` option to import the theme rather than importing it into nix.
I also had to update the mpv port because this relies on a recent change that puts all the settings in a single file because script-opts files cannot include other files, but their options can be set with the `script-opts` option in `mpv.conf`
> fix(home-manager/mpv): avoid IFD

- modules/home-manager/lazygit.nix
Sets `$LG_CONFIG_FILE` to merge the default lazygit config file and the theme file rather than importing the theme file into nix.
> fix(home-manager/lazygit): avoid IFD

- modules/home-manager/dunst.nix
Uses dunst's drop-in feature to set the theme rather than importing it into nix.
This approach has the drawback that theme settings are now potentially slightly more inconvenient to override. The theme drop-in overrides settings from `dunstrc`, but it can itself be overridden by another drop-in that is after it in lexical order.
I added a `prefix` option to make it more convenient to have the catppuccin drop-in appear in a certain spot in lexical order if the user has multiple drop-ins they wish to use with dunst.
Currently blocked on https://github.com/nix-community/home-manager/pull/5710
> fix(home-manager/dunst): avoid IFD

- modules/home-manager/tmux.nix
[catppuccin/tmux](https://github.com/catppuccin/tmux) recently switched the spelling of flavour to flavor in https://github.com/catppuccin/tmux/pull/277
> fix(tmux): follow upstream spelling change

- .sources/sources.json
- modules/home-manager/all-modules.nix
- modules/home-manager/spotify-player.nix
- tests/home.nix
I have an issue with the theme:
The `playback_metadata` component has the same color as the background and is therefore not legible.
But this should be fixed in the [catppuccin repo](https://github.com/catppuccin/spotify-player), right?
> feat(home-manager): add support for spotify-player

- modules/home-manager/lazygit.nix
Lazygit would fail to load becase the wrong path was being generated to the configuration file on darwin systems when XDG wasn't enabled.
Fixes #312
> fix(home-manager/lazygit): support darwin without XDG

- modules/home-manager/k9s.nix
k9s expects configuration files on OS X to live in `~/Library/Application Support/k9s` instead of `~/.config.k9s`. This commit handles the case where the module is built for a darwin system with xdg disabled.
See: https://github.com/catppuccin/nix/issues/310
> fix(home-manager/k9s): support darwin without XDG

- dev/flake.lock
- docs/src/faq.md
- modules/home-manager/kitty.nix
also removed kitty from the IFD section in the faq, as `themeFile` doesn't use IFD
> fix(home-manager/kitty): use new `themeFile` option on 24.11

- modules/home-manager/all-modules.nix
- modules/home-manager/freetube.nix
- tests/home.nix
Adds support for theming FreeTube. The colors are built-in, so no new sources have been added.
Also, FreeTube supports two different accent colors, so I added a `secondaryAccent` option. I made it default to FreeTube's `accent` rather than the global `accent` setting because it seemed like it would be intuitive behavior to have them match if, say, only `accent` is overridden.
> feat(home-manager): add support for freetube

- .sources/sources.json
- modules/home-manager/all-modules.nix
- modules/home-manager/obs-studio.nix
- tests/darwin.nix
- tests/home.nix
Hello, I wrote a little module for obs-studio, closing https://github.com/catppuccin/nix/issues/321
> feat(home-manager): add support for obs-studio

- .sources/sources.json
- modules/home-manager/mako.nix
I created a pr in catppuccin/mako to add accent color support.
I don't know if it will get merged, but if it will, I can update the sources and it will be available here too.
If it doesn't, just ignore this pr.
This pr is also like a "reminder" to let you know that mako might "break" if the ipstream pr gets merged but this doesn't.
> feat(mako): add accent color support

- README.md
Upstream removed the ifd in home-manger/kitty, #337 made the required changes and removed it from the ifd faq in docs/src/faq.md but not README.md.
> docs: remove kitty from README ifd faq

- modules/home-manager/hyprland.nix
- modules/home-manager/hyprlock.nix
Ensure accents are defined before user vars
Partially reverts 512306ae
See https://github.com/catppuccin/nix/pull/299#discussion_r1706992419
> fix(home-manager/hyprland): import accents from file

- modules/home-manager/kvantum.nix
Fix for kvantum module, which uses an updated catppuccin-kvantum package that changed from uppercase enums to lowercase.
Closes #357
> fix(home-manager/kvantum): don't uppercase accents and flavors in override

- .sources/sources.json
- modules/home-manager/yazi.nix
Updates the module to support the newly added accent variants (https://github.com/catppuccin/yazi/pull/12).
> feat(home-manager): update yazi for accent support

- modules/home-manager/fcitx5.nix
Hello, the theme paths and names for catppuccin's [fcitx5](https://github.com/catppuccin/fcitx5) got updated to include accents, so this has to be updated here, and should be done similarly in https://github.com/catppuccin/nix/pull/221 to also include the accents
> feat(home-manager/fcitx5): add accent support

- tests/darwin.nix
Fails to build currently
Fixes https://github.com/catppuccin/nix/issues/382
> chore(tests): disable spotify-player on darwin

- modules/lib/default.nix
See https://github.com/NixOS/nixpkgs/commit/062945b725875167a24b11c4c1f2ba8e7623d3d6
Fixes https://github.com/catppuccin/nix/issues/399
As a workaround, you can do
```diff
-catppuccin.url = "github:catppuccin/nix";
+catppuccin.url = "github:catppuccin/nix?ref=pull/400/head";
```
in your flake.nix
> chore(lib): improve mergeEnums

- dev/flake.lock
• Updated input 'catppuccin-v1_1':
'https://api.flakehub.com/f/pinned/catppuccin/nix/1.1.0/01930ce8-240c-7eee-a23c-4c7873bdedc9/source.tar.gz?narHash=sha256-O4GA8GMA9bGJwBW1U6rahT4wJWC6YweLZeGo0i1TS7U%3D' (2024-11-08)
→ 'https://api.flakehub.com/f/pinned/catppuccin/nix/1.1.1/0193bdc0-b045-7eed-bbec-95611a8ecdf5/source.tar.gz?narHash=sha256-pCWJgwo77KD7EJpwynwKrWPZ//dwypHq2TfdzZWqK68%3D' (2024-12-13)
> chore: bump dev flake to v1.1.1

- dev/flake.lock
• Updated input 'catppuccin-rolling':
'github:catppuccin/nix/7e17c6946516d6599b9ccd4b04447e6567506a1e?narHash=sha256-KyS4QJ/zfruToq3NmxKQQ2/4WNlzznMaGNO7Aq1kozQ%3D' (2024-12-13)
→ 'github:catppuccin/nix/dcc1cbe936d053efca73483cfca81a35d2318c6b?narHash=sha256-TzJewMe7yoVPUOMM6Mi0ptN6dTwSe9tY1UJKUM6rxpE%3D' (2024-12-19)
> chore: bump rolling input in dev flake

- CHANGELOG.md
- cliff.toml
- **chore: add changelog bump instructions**
- **chore: v1.2.0**
> chore: v1.2.0

- modules/home-manager/zed-editor.nix
> fix(home-manager/zed): use correct names

- docs/src/faq.md
* https://github.com/catppuccin/nix/pull/371
oh and we need a port for NüschtOS Search :)
> docs(FAQ): move to catppuccin namespace

- modules/home-manager/gtk.nix
closes https://github.com/catppuccin/nix/issues/428
> fix(home-manager/gtk): pass flavor and not variant

- modules/home-manager/all-modules.nix
- modules/home-manager/wlogout.nix
- modules/tests/darwin.nix
- modules/tests/home.nix
- pkgs/sources.json
- pkgs/wlogout/package.nix
Adds support for wlogout.
Extra options I added:
- `iconStyle`, which lets the user specify whether to use the wlogout or wleave-style icons that come with the theme.
- `extraStyle`, which lets the user add extra CSS to ~/.config/wlogout.css
In order for the svg icons to display properly, [`pkgs.librsvg`](https://search.nixos.org/packages?channel=unstable&show=librsvg&from=0&size=50&sort=relevance&type=packages&query=librsvg) needs to be in [`programs.gdk-pixbuf.modulePackages`](https://search.nixos.org/options?channel=unstable&show=programs.gdk-pixbuf.modulePackages&from=0&size=50&sort=relevance&type=packages&query=gdk-pixbuf), but I am not sure if I should add an assertion or warning or something or not.
> feat(home-manager): init wlogout module

- modules/home-manager/alacritty.nix
We can use the `import` setting within alacritty to import the file with the least presidence, this is beacuse anything within the `alacritty.toml` file has greater precedence and other files imported will be loaded after the imported catppuccin theme beacuse of the `lib.mkBefore`.
For futher reading consult
https://alacritty.org/config-alacritty.html#s1
> refactor(home-manager/alacritty): remove importTOML

- modules/global.nix
closes https://github.com/catppuccin/nix/issues/444
> feat: global cachix option

- modules/home-manager/alacritty.nix
This pull request fixes an issue in the Home-Manager Alacritty module related to the placement of the `import` config key in the generated `alacritty.toml` configuration file.
The current implementation of the Alacritty module defines the `import` config key as follows:
```nix
settings.general.import = lib.mkBefore [ "${sources.alacritty}/catppuccin-${cfg.flavor}.toml" ];
```
This results in a configuration file with the following structure:
```toml
[general]
import = ["..."]
```
However, according to Alacritty's documentation, global settings like import must be declared at the top level of the TOML file. They should not be nested under a [general] section. The correct structure should be:
```toml
import = ["..."]
[other_options]
...
```
This pull request modifies the module to define …
> fix(home-manager/alacritty): remove the `general` setting option

- modules/home-manager/alacritty.nix
Reverts catppuccin/nix#450
https://github.com/catppuccin/nix/pull/450#issuecomment-2571501256
> revert: "fix(home-manager/alacritty): remove the `general` setting option"

- modules/home-manager/all-modules.nix
- modules/home-manager/chrome.nix
- modules/tests/darwin.nix
- modules/tests/home.nix
[catppuccin/chrome](https://github.com/catppuccin/chrome)
> Add support for chromium browsers

- modules/home-manager/helix.nix
- modules/home-manager/yazi.nix
Removes IFD. This shouldn't break themes. but if someone was previously using some form of `lib.mkForce` on these settings they will break.
> home-manager: remove IFD from helix and yazi

- flake.lock
- modules/home-manager/all-modules.nix
- modules/home-manager/ghostty.nix
- modules/tests/darwin.nix
- modules/tests/home.nix
- pkgs/sources.json
> feat(home-manager): add support for ghostty

- modules/home-manager/all-modules.nix
- modules/home-manager/lsd.nix
- modules/tests/home.nix
- pkgs/sources.json
Add support for the LSD program.
In particular, the module defines the `programs.lsd.colors` option to be correspondent `themes/catppuccin-<flavor>/colors.yaml` file of the [LSD port](https://github.com/catppuccin/lsd).
> feat(home-manager): add support for lsd

- pkgs/catwalk/package.nix
Using `buildRustPackage` without it is deprecated
> fix(catwalk): enable useFetchCargoVendor

- modules/nixos/tty.nix
likely forgotten when we moved to the namespace
> refactor: console -> tty

- modules/home-manager/default.nix
- modules/nixos/default.nix
this *should* help prevent errors from utilising the wrong class for the diffrent system types. e.g. darwin trying to use nixos modules
> chore: set module class

- modules/nixos/all-modules.nix
- modules/nixos/gitea.nix
- modules/tests/nixos.nix
- pkgs/gitea/package.nix
Requires fetching release artifacts or building the theme from source (similar to #149)
> feat(nixos): add support for gitea/forgejo

- .github/workflows/ci.yml
- .github/workflows/update-locks.yml
I recently notice we were not getting updates for ports. Seems to have been dropped in https://github.com/catppuccin/nix/commit/115c3de5635c257bd2a723e06f8262a5edd66d9c. This PR adds that back and runs the test suite against those changes
> ci: add update-locks

- renovate.json
Forgot to remove this in https://github.com/catppuccin/nix/pull/476. It's what was meant to replace the workflow, but obviously doesn't work :/
> ci: disable nix in renovate

- modules/home-manager/neovim.nix
This commit adds an `extraConfig` option to the neovim options that gets dynamically converted into a Lua table and passed to the setup function which is useful for configuring things like italics, transparent_background,...
Fixes this issue: https://github.com/catppuccin/nix/issues/259
> feat(home-manager/neovim): add option for custom settings

- .github/workflows/ci.yml
- .github/workflows/update-locks.yml
`workflow_call` only works for jobs, not steps
> ci: use workflow_dispatch over workflow_call in update-locks

- pkgs/paws.py
By default [`datetime.datetimefromtimestamp`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) uses localtime , so to prevent more "spammy" sources.json changes, like https://github.com/catppuccin/nix/pull/501, lets set the timezone to UTC.
> fix(pkgs/paws): set timezone to UTC for fetcher

- modules/home-manager/all-modules.nix
- modules/home-manager/wezterm.nix
- modules/tests/home.nix
- pkgs/sources.json
- pkgs/wezterm/package.nix
This adds support for WezTerm theme. There are no specific option fo themes in the wezterm home-manager module so I used `extraConfig`.
> feat(home-manager): add support for wezterm

- modules/home-manager/all-modules.nix
- modules/home-manager/swaync.nix
- modules/tests/darwin.nix
- modules/tests/home.nix
- pkgs/swaync/package.nix
Ready-to-use css files are only provided as release artifacts.
We could also build these ourselves, but would need to manually update the `npmDepsHash`.
The default font used in the theme is "Ubuntu Nerd Font".
Adding it to `home.packages` is not possible as I query that for `enable` and thus would result in infinite recursion.
For the option name I referred to https://github.com/nix-community/home-manager/pull/4249 and https://github.com/nix-community/home-manager/pull/5345.
> feat(home-manager): add support for swaync

- flake.nix
Fixes: https://github.com/catppuccin/nix/pull/519
> chore: add `default` nixos and home-manager module

- flake.nix
This is the official naming of home-manager modules, as recognized by `nix flake check`
> refactor: deprecate `homeManagerModules` for `homeModules`

- modules/home-manager/all-modules.nix
- modules/home-manager/sioyek.nix
- modules/tests/home.nix
- pkgs/sources.json
Hai, I've added a module for sioyak. 
Although I'm not sure what is the best way to handle when `programs.sioyek.config.startup_commands` already has a value.
```shell
error: The option `home-manager.users.n.programs.sioyek.config.startup_commands' has conflicting definition values:
- In `/nix/store/saj8wg1a0iwxynwg2viywh57mfxqbjia-source/modules/home-manager/sioyek.nix': "toggle_custom_color;"
- In `/nix/store/6p5182xf5wbqvrysrraj9kcbm101yjsq-source/home/programs.nix': "toggle_scrollbar"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```
> feat(home-manager): add support for sioyak

- flake.nix
It seems pretty established that `default` should stay valid, however when using it, we get the following warning 
```
trace: evaluation warning:
Obsolete Flake attribute `catppuccin.homeManagerModules.catppuccin' is used.
It was renamed to `catppuccin.homeModules.catppuccin`'.
```
> flake: `homeModules.default` should not print warning

- pkgs/paws.py
between nix 2.26 and 2.28 theres a difference in the output json from `nix flake prefetch`
nix 2.26: 
```json
{
"hash": "sha256-JYHsWUKKBzYEc5iSiyYsYm5Kz73PPN0php0JfR9wMxg=",
"locked": {
"__final": true,
"lastModified": 1744992325,
"narHash": "sha256-JYHsWUKKBzYEc5iSiyYsYm5Kz73PPN0php0JfR9wMxg=",
"owner": "catppuccin",
"repo": "atuin",
"rev": "bd403cf7f0324aafc3f2462aeb9c2be6e230c9ac",
"type": "github"
},
"original": {
"owner": "catppuccin",
"repo": "atuin",
"type": "github"
},
"storePath": "/nix/store/0b398ha6q0gbzjswbdxhh8r1fgiyjrgf-source"
}
```
nix 2.18:
```json
{
"hash": "sha256-JYHsWUKKBzYEc5iSiyYsYm5Kz73PPN0php0JfR9wMxg=",
"locked": {
"__final": true,
"lastModified": 1744992325,
"owner": "catppuccin",
"repo": "atuin",
"rev": "bd403cf7f0324aafc3f2462aeb9c2be6e230c9ac",
"type": …
```
> fix(paws): use hash instead of narHash

- modules/home-manager/zsh-syntax-highlighting.nix
Will be deprecated shortly, switch to new configuration before users get warnings from it https://github.com/nix-community/home-manager/pull/6841
Using `mkOrder 950` to keep position same in generated output as before. (Top of the `initExtra` location.
> refactor: zsh-syntax-highlighting initExtra -> initContent

- modules/home-manager/mako.nix
> fix(home-manager/mako): use settings instead of extraConfig

- modules/home-manager/mako.nix
see: https://github.com/nix-community/home-manager/pull/7024
closes https://github.com/catppuccin/nix/issues/564
> fix(mako): deprecated settings.criteria

- pkgs/gitea/package.nix
The `gitea` package seems to be out of sync with the most recent release from `catppuccin/gitea` https://github.com/catppuccin/gitea/releases/tag/v1.0.2
> chore: update gitea package to v1.0.2

- modules/home-manager/vscode.nix
- modules/home-manager/zed-editor.nix
- modules/lib/default.nix
This transformation is used in a few places, so it would be nice to have a common library function for it. (Also would be useful for end users as part of a public `lib` interface, if that's on the table.)
> refactor: add `lib.mkFlavorName`

- modules/home-manager/all-modules.nix
- modules/home-manager/firefox.nix
- modules/tests/home.nix
- pkgs/firefox/package.nix
- pkgs/firefox/write-themes-to-json.patch
- pkgs/sources.json
Supersedes #451
Opening a new PR as #451 hasn't seen activity in a few months and I took this in a different direction
This adds Firefox Color support for Firefox based browsers supported by Home Manager's mkFirefoxModule helper (`firefox`, `librewolf` & `floorp`)
This uses a different option path to the previous PR, allowing for per-profile config
```
catppucin.<browser>.profiles.<profile>.theme
```
~~Everything is under the `theme` option to allow for seperate userstyle configuration options under the `userstyles` option (see #591)~~
Some considerations:
Firefox Color must currently be installed by the user manually, but we have two other options for this: we could package and install Firefox Color ourselves, or do what [Stylix does and use …
> feat(home-manager): add theme support for firefox-based browsers

- modules/home-manager/all-modules.nix
- modules/home-manager/vesktop.nix
- modules/tests/home.nix
[catppuccin/discord](https://github.com/catppuccin/discord) mainly uses GitHub dists for the discord themes.
I don't see a reason to include it in sources. The only themes that will be generated are flavor-only themes [(example)](https://github.com/catppuccin/discord/blob/main/themes/mocha.theme.css) and those don't do more than importing the dist file.
So I decided to import the theme directly.
If you have any suggestions, let me know.
> feat(home-manager): add support for vesktop

- modules/home-manager/all-modules.nix
- modules/home-manager/mangohud.nix
- modules/tests/darwin.nix
- modules/tests/home.nix
- pkgs/sources.json
Hello,
I've added support for mangohud.
Home-Manager provides a mangohud module and a settings option for it, but we can't import the config file like we do with toml, json or ini.
MangoHud doesn't have an include/import option in the MangoHud config, so we must replace the whole config.
There is an option called preset, but this didn't feel right either.
If you have any suggestions or don't like this solution, please let me know.
Have a great day!
> feat(home-manager): add support for mangohud

- modules/home-manager/zsh-syntax-highlighting.nix
There is no advantage to using builtins.hasAttr over ? in this case. There is no dynamic expression providing the attr to check for.
Furthermore, it is better to check for that attr under options rather than config for these reasons:
* it's easier to avoid infinite recursion when actually mutating a config attribute that you're checking by using the option only, and not the config; not necessarily that this would be caused by this, but as a general reason for doing it when you can
* checking the config attribute causes evaluation of the relevant modules to find anything that sets the attribute, but you only care that it exists or is defined at all. It is more efficient to only check options since it only needs to check modules that have option definitions.
and so it's better form to do it …
> refactor(home-manager/zsh-syntax-highlighting): options and use ? instead of config and hasAttr

- flake.lock
- pkgs/vscode/package.nix
Fixes https://github.com/catppuccin/nix/issues/612
I only ran `nix build .#vscode` to test this change
> chore: update flakes and add `fetcherVersion`

- pkgs/catwalk/package.nix
- pkgs/whiskers/package.nix
This pull request makes a small change by removing the `useFetchCargoVendor` attribute from two `rustPlatform.buildRustPackage` definitions.
It was raising a warning like this one:
```
evaluation warning: buildRustPackage: `useFetchCargoVendor` is non‐optional and enabled by default as of 25.05, remove it
```
So here this fix follows the given instruction.
* Removed the `useFetchCargoVendor` attribute from the `rustPlatform.buildRustPackage` definition in `pkgs/catwalk/package.nix`.
* Removed the `useFetchCargoVendor` attribute from the `rustPlatform.buildRustPackage` definition in `pkgs/whiskers/package.nix`.
> fix: useFetchCargoVendor is non-optional and enabled by default as of 25.05

- .github/workflows/format.yml
- dev/flake.nix
- modules/home-manager/firefox.nix
~~Generally, using conditional option merging to apply these settings at
the submodule level:~~
~~- Breaks standalone evaluation of the homeModule (like in our docs)~~
~~- Allows for strange effects that only happen conditionally, like https://github.com/catppuccin/nix/pull/627#issuecomment-3134735931~~
The above is still a point I'd like to make, but conditional option merging is required here. We just need to be careful with it
Fixes #631, as well as a regression from #627
> fix(home-manager/firefox): only apply to profiles specified

- modules/home-manager/swaync.nix
- modules/home-manager/thunderbird.nix
Considering 24.11 has been EOL for a while at this point, this is probably fine
> chore(modules)!: drop support for nixpkgs 24.11

- default.nix
- pkgs/sources.json
Upstream [has been udpated](https://github.com/catppuccin/foot/pull/20), without this change every time a foot terminal is started an error is printed.
@getchoo I'm assuming that `catppuccin` targets `nixos-unstable`, this change will now show an error when starting version `1.22.3` (on `nixos-25.05`)
> fix(foot): update port for v1.22.3

- flake.nix
- shell.nix
https://wetdry.world/@getchoo/114962325064525100
We could also just...stop using a development Flake again, eat a home-manager input in the root Flake, and move all the outputs to there? This would only fix compatibility with Lix, though
Maybe something with traditional Nix, grabbing Nixpkgs from our root flake.lock, and pinning home-manager elsewhere? This would fix both, but sounds painful.
I don't know. This works for now.
> chore(devshell): pin nix

- modules/home-manager/mako.nix
Update the mako module to use mako's new `include` option instead of using IFD and manually assigning options.
I removed the check for Home Manager's `services.mako.settings` option because this flake's mako module now strictly relies on it and we moved to following Nixpkgs/NixOS/Home Manager's version scheme anyways.
> fix(home-manager/mako): remove ifd

- docs/content/docs/Getting Started/flakes.mdx
`trace: evaluation warning: Obsolete Flake attribute 'catppuccin.homeManagerModules.catppuccin' is used. It was renamed to 'catppuccin.homeModules.catppuccin'.`
The first two examples on the page have it correct, but in the "end flake", it's using the old attribute.
> docs: Update obsolete flake attribute for importing catppuccin

- modules/home-manager/wezterm.nix
Use catppuccin config to set options in the catppuccin WezTerm plugin. This also enables support for accent. The plugin's `sync` option could also be used for future support for light and dark flavors.
---
We no longer set `colorSchemes` for WezTerm but I don't think it ever worked as intended. The colorSchemes option from home-manager [puts values in the set `colors`](https://github.com/nix-community/home-manager/blob/6159629d05a0e92bb7fb7211e74106ae1d552401/modules/programs/wezterm.nix#L113-L118) which results in the output file having tables like `[colors.colors]` ([output file with default options](https://gist.github.com/signegrau/af52d601053d9683be2a26f62913265b#file-catppuccin-mocha-toml)). WezTerm does not like this as seen in the debug overlay
```
23:21:52.030 WARN …
```
> feat(wezterm): set flavor and accent as plugin options

- modules/home-manager/kvantum.nix
As discussed here, setting `QT_QPA_PLATFORMTHEME` may be unnecessary: https://github.com/catppuccin/nix/issues/430#issuecomment-3346642996
But more importantly, the option enforced by the assertion simply does not work for certain platforms. This will leave the user's system in a broken state while at the same time preventing that very user from fixing it. It's *very* frustrating situation to be in.
For now, I propose simply removing the assertion until we have more data on what works and what doesn't.
On the other hand, I chose to leave the `QT_STYLE_OVERRIDE` assertion untouched because I believe it should be correct based on my experience and various online discussions I've come across.
If anyone have experience with setting Kvantum across different platforms (e.g. GNOME, KDE, plain …
> fix(home-manager/kvantum): remove platform theme assertion
