catppuccin/nix

flake.nix
=> fix: set correct path for modules

modules/home-manager/default.nix, modules/home-manager/gtk.nix
this adds support for the [gtk](https://github.com/catppuccin/gtk) theme, as well as an accent option for future use in other modules :)
=> add support for gtk

modules/home-manager/default.nix, modules/home-manager/helix.nix
this adds support for the [helix](https://github.com/catppuccin/helix) theme
=> add support for helix

modules/home-manager/bottom.nix, modules/home-manager/default.nix
this adds support for the [bottom](https://github.com/catppuccin/bottom) theme
=> add support for bottom

README.md
this is a draft for now since of course i will need feedback, but i think this is a good step towards getting this into the org
so far i've added instructions, changed most links to point to catppuccin/nix, and added a bit to the q&a
=> complete readme template

modules/home-manager/default.nix, modules/home-manager/polybar.nix
this adds support for the [polybar](https://github.com/catppuccin/polybar) theme
=> add support for polybar

modules/home-manager/alacritty.nix, modules/home-manager/default.nix
this adds support for the [alacritty](https://github.com/catppuccin/alacritty) theme
=> add support for alacritty

modules/home-manager/btop.nix, modules/home-manager/default.nix
this adds support for the [btop](https://github.com/catppuccin/btop) theme
=> add support for btop

modules/home-manager/default.nix, modules/home-manager/tmux.nix
this adds support for the [tmux](https://github.com/catppuccin/tmux) theme
=> add support for tmux

modules/home-manager/default.nix, modules/home-manager/sway.nix
this adds support for the [sway](https://github.com/catppuccin/sway) theme
=> add support for sway

modules/home-manager/default.nix, modules/home-manager/neovim.nix
this adds support for the [neovim](https://github.com/catppuccin/nvim) theme
=> add support for neovim

modules/nixos/grub.nix
title, just want to do it for consistency
=> use mkCatppuccinOpt in grub

README.md
=> add link to nixos modules

modules/home-manager/alacritty.nix, modules/home-manager/bottom.nix, modules/home-manager/btop.nix, modules/home-manager/default.nix, modules/home-manager/gtk.nix, modules/home-manager/helix.nix, modules/home-manager/polybar.nix, modules/home-manager/tmux.nix, modules/lib/default.nix, modules/nixos/default.nix, modules/nixos/grub.nix
continuation of #30 and helping to complete #23
=> format with nixpkgs-fmt

modules/home-manager/gtk.nix
=> fix(gtk): capitalize "Light" and "Dark"

modules/home-manager/bat.nix
Closes #42
https://github.com/nix-community/home-manager/commit/44635279a0dfca43d2b980422f295def1aca0c08
=> fix(home-manager/bat): use attrset for theme specification

.github/dependabot.yml, .github/workflows/update-docs.yml
- ci: fix revision for docs generation
- ci: add dependabot
=> ci: fix revision for docs generation & add dependabot

_sources/generated.json, _sources/generated.nix, modules/home-manager/default.nix, modules/home-manager/zathura.nix, nvfetcher.toml, test.nix
Adds support for zathura. Resolves #41.
=> feat(home-manager): init zathura module

modules/home-manager/gtk.nix, test.nix
Believe it or not, [Catppuccin has cursors!](https://github.com/catppuccin/cursors)
=> gtk: add cursor theming support

modules/home-manager/bat.nix
https://github.com/catppuccin/bat/pull/5 changed the repo structure and theme naming.
=> fix(bat): match refactors in source

_sources/generated.json, _sources/generated.nix, modules/home-manager/delta.nix, nvfetcher.toml, test.nix
=> feat(home-manager): init delta module

_sources/generated.json, _sources/generated.nix, modules/home-manager/swaylock.nix, nvfetcher.toml, test.nix
=> feat(home-manager): init swaylock module

_sources/generated.json, _sources/generated.nix, modules/home-manager/imv.nix, nvfetcher.toml, test.nix
=> feat(home-manager): init imv module

_sources/generated.json, _sources/generated.nix, modules/home-manager/gitui.nix, nvfetcher.toml, test.nix
Adds support for gitui. Resolves #13.
=> feat(home-manager): init gitui module

_sources/generated.json, _sources/generated.nix, modules/home-manager/rofi.nix, nvfetcher.toml, test.nix
=> feat(home-manager): add support for rofi

_sources/generated.json, _sources/generated.nix, modules/home-manager/dunst.nix, nvfetcher.toml, test.nix
Adds support for dunst. Resolves #99
=> feat(home-manager): add support for dunst

_sources/generated.json, _sources/generated.nix, modules/home-manager/k9s.nix, nvfetcher.toml, test.nix
Add support for the `k9s` home-manager module
=> feat(home-manager): init k9s module

_sources/generated.json, _sources/generated.nix, modules/home-manager/fcitx5.nix, nvfetcher.toml, test.nix
=> feat(home-manager): init fcitx5 module

_sources/generated.json, _sources/generated.nix, modules/home-manager/mpv.nix, nvfetcher.toml, test.nix
=> feat(home-manager): init mpv module

_sources/generated.json, _sources/generated.nix, modules/home-manager/tofi.nix, nvfetcher.toml, test.nix
=> feat(home-manager): add support for tofi

modules/nixos/sddm.nix, test.nix
=> feat(nixos): sddm

modules/home-manager/btop.nix, modules/home-manager/fcitx5.nix, modules/home-manager/fish.nix, modules/home-manager/gtk.nix, modules/home-manager/k9s.nix, modules/home-manager/micro.nix, modules/home-manager/yazi.nix, modules/lib/default.nix
fixes #178
this isn't required on darwin either
=> fix(home-manager): remove xdg.enable assertions

.github/workflows/publish.yml
=> ci: publish to flake registries on tag

dev/option-doc.nix, modules/home-manager/globals.nix, modules/nixos/globals.nix
- **fix: set nixos release in mkOptionDoc**
- **fix(modules): shorten defaultText for `catppuccin.sources`**
=> fix(modules): shorten defaultText for `catppuccin.sources`

dev/flake.lock, dev/flake.nix, modules/home-manager/globals.nix, modules/home-manager/tofi.nix, modules/lib/default.nix, modules/nixos/globals.nix, modules/nixos/sddm.nix
draft until the actual release
=> feat(modules)!: bump minimum supported release to 24.05

modules/home-manager/gtk.nix
lovely init 
ref https://github.com/NixOS/nixpkgs/commit/914a9ca2c8a0d2cc934bc8a63589346828cd2c75
=> chore(home-manager): cursors are now lowercase

modules/home-manager/hyprland.nix
Implements my suggestion from https://github.com/catppuccin/nix/pull/212#issuecomment-2153410194
Felt like it would be good as a separate PR.
=> feat(home-manager): set hyprcursor

modules/home-manager/all-modules.nix, modules/home-manager/cursor.nix, modules/home-manager/gtk.nix, modules/home-manager/hyprland.nix, modules/lib/default.nix
=> feat(home-manager)!: add support for global cursors

modules/home-manager/swaylock.nix
fixes #205
read included comment for an explanation ~~and witness me losing my marbles~~
=> fix(home-manager): don't let swaylock cause infinite recursion

README.md
=> docs: update link to `catppuccin.enable`

modules/home-manager/hyprland.nix
=> fix(home-manager/hyprland): inherit cursor size, unset hyprcursor env vars

modules/home-manager/hyprland.nix
fixes https://github.com/catppuccin/nix/issues/308
=> fix(home-manager/hyprland): allow merging `sources` option

modules/home-manager/gtk.nix
=> fix(home-manager/gtk): support all tweaks

README.md, docs/src/faq.md
Adds an FAQ for IFD as described in #172.
=> docs: add IFD FAQ

.sources/sources.json, modules/home-manager/aerc.nix, modules/home-manager/all-modules.nix, tests/home.nix
Adds support for https://github.com/catppuccin/aerc.
=> feat(home-manager): add support for aerc

docs/src/getting-started/flakes.md
found a invalid link and decided to fix it :)
=> docs: fix invalid link

README.md
Closes https://github.com/catppuccin/nix/issues/396
=> docs: link to new options search

CHANGELOG.md, README.md, cliff.toml
- **docs: filter out non-api changing commits**
- **chore: v1.1.1**
=> chore: v1.1.1

modules/home-manager/hyprland.nix
re: https://github.com/catppuccin/nix/pull/371#issuecomment-2555603718
@khaneliman are you willing to test?
=> fix(home-manager/hyprland): rename accent

modules/home-manager/all-modules.nix, modules/home-manager/zed-editor.nix, tests/home.nix
closes https://github.com/catppuccin/nix/issues/317
=> feat(home-manager): add support for zed-editor

modules/home-manager/zed-editor.nix
thank you for finding this soopy
=> fix(home-manager/zed): correctly apply italics

README.md
=> docs: show new option namespace

modules/home-manager/fcitx5.nix
closes https://github.com/catppuccin/nix/issues/434
=> fix(home-manager/fcitx5): ajust source

README.md
just noticed I hadn't included the changes from #423 in the README
=> docs(README): sync FAQ with site

modules/home-manager/zed-editor.nix
cc: @uncenter as the person who reported the accent issue to me
=> fix(home-manager/zed): correctly enable & select accent

modules/home-manager/all-modules.nix, modules/home-manager/thunderbird.nix, modules/tests/darwin.nix, modules/tests/home.nix, modules/tests/nixos.nix, pkgs/sources.json
=> feat(home-manager): add support for thunderbird

modules/home-manager/zed-editor.nix
* fixes frappe not working
* adds support for icons
=> feat(home-manager/zed-editor): icon support

modules/home-manager/thunderbird.nix, modules/tests/home.nix
fix https://github.com/catppuccin/nix/commit/2e2cd909e1645bb5c5f7824326ec7b7abe4c6cbe#commitcomment-153441831
=> fix: assert home-manager version for thunderbird module

default.nix, pkgs/aerc/package.nix, pkgs/alacritty/package.nix, pkgs/buildCatppuccinPort/package.nix, pkgs/cursors/package.nix, pkgs/delta/package.nix, pkgs/fcitx5/package.nix, pkgs/grub/package.nix, pkgs/gtk/package.nix, pkgs/k9s/package.nix, pkgs/kvantum/package.nix, pkgs/lazygit/package.nix, pkgs/micro/package.nix, pkgs/palette/package.nix, pkgs/paws.py, pkgs/plymouth/package.nix, pkgs/rofi/package.nix, pkgs/sddm/package.nix, pkgs/sources.json, pkgs/spotify-player/package.nix, pkgs/wlogout/package.nix, pkgs/zathura/package.nix, pkgs/zed/package.nix
=> refactor: add `catppuccin-` prefix to `buildCatppuccinPort` pnames

pkgs/rofi/package.nix
@typedrat for testing
closes https://github.com/catppuccin/nix/issues/496
=> fix(pkgs/rofi): remove import at build

docs/theme/catppuccin.css, docs/theme/index.hbs
=> fix(docs): theming 

.github/workflows/ci.yml, .github/workflows/format.yml, .github/workflows/publish.yml, .github/workflows/update-locks.yml, .github/workflows/website.yml, dev/README.md
- **ci: actually update cachix/install-nix-action action to v31**
- **docs: update nix 2.26 dev flake warning**
=> ci: actually update cachix/install-nix-action action to v31

modules/home-manager/all-modules.nix, modules/home-manager/vscode.nix, modules/tests/home.nix, pkgs/vscode/package.nix
Closes https://github.com/catppuccin/nix/issues/374
=> feat(home-manager): add support for vscode

README.md
Also tries to fix #462
We can't really provide a full tutorial here on when to place what in your configuration.nix, home.nix, or flake.nix (as it will largely depend on the person), but hopefully specicying the "configuration" will direct people to the first two rather than possibly their Flake
=> docs(README): link to IFD tracking issue

modules/home-manager/lazygit.nix
IFD > breakage in some cases
Fixes: https://github.com/catppuccin/nix/issues/455
Refs: 66f4ea1
=> revert: "fix(home-manager/lazygit): avoid IFD"

modules/tests/nixos.nix
This reverts commit f833a338ff6c091c84e041ee77ce88f8b242ca79.
Thanks to https://github.com/catppuccin/nix/pull/512
=> Revert "fix(tests): disable forgejo (#505)"

modules/home-manager/hyprlock.nix, pkgs/hyprlock/package.nix, pkgs/sources.json
=> feat(home-manager/hyprlock): allow using default config for port

modules/home-manager/all-modules.nix, modules/home-manager/qutebrowser.nix, modules/tests/home.nix, pkgs/qutebrowser/package.nix, pkgs/sources.json
https://github.com/catppuccin/qutebrowser
=> feat(home-manager): add support for qutebrowser

docs/mk-search.nix, modules/home-manager/vscode.nix, pkgs/sources.json, pkgs/vscode/package.nix
closes https://github.com/catppuccin/nix/issues/520
=> feat(home-manager/vscode): allow configuration of build

modules/home-manager/all-modules.nix, modules/home-manager/atuin.nix, pkgs/sources.json
closes https://github.com/catppuccin/nix/issues/540
=> feat(home-manager): add atuin

modules/home-manager/fcitx5.nix
see: nix-community/home-manager#6885
=> fix(home-manager/fcitx5): support new enable option

README.md
homeManagerModules -> homeModules
=> docs: update home-manager module name in readme

modules/home-manager/zed-editor.nix
closes https://github.com/catppuccin/nix/issues/573
=> feat(home-manager/zed-editor): add ablity to enable/disable icons

dev/flake.lock, dev/flake.nix, flake.lock, modules/global.nix, modules/home-manager/bat.nix, modules/home-manager/cursors.nix, modules/home-manager/fish.nix, modules/home-manager/freetube.nix, modules/home-manager/kitty.nix, modules/home-manager/obs.nix, modules/home-manager/yazi.nix, modules/lib/default.nix, modules/tests/darwin.nix, modules/tests/home.nix, pkgs/buildCatppuccinPort/package.nix
i just need ci to run the tests really :p, im on darwin right now
=> chore: update to 25.05

modules/home-manager/fcitx5.nix, modules/nixos/fcitx5.nix, pkgs/fcitx5/package.nix
closes https://github.com/catppuccin/nix/issues/598
=> feat(fctix5): add enableRounded option

modules/home-manager/lazygit.nix
Prevents IFD without reintroducing the issue described in https://github.com/catppuccin/nix/issues/455
=> chore(lazygit): remove IFD

modules/home-manager/vscode.nix, pkgs/vscode-icons/package.nix
closes https://github.com/catppuccin/nix/issues/518
=> feat(home-manager/vscode-icons): init

modules/home-manager/firefox.nix
Supersedes #606 
Closes #602
Applies configuration by setting new default values for home-manager's Firefox profiles submodules, rather than through `config` directly. This approach makes no assumption of profile names, and will apply to all profiles if global enable is used
Adds a global configuration for all profiles under `catppuccin.<browser>`. Per profile configuration is still possible under `catppuccin.<browser>.profiles.<profile>` and takes priority over global config
This PR makes it easier for anyone to use the module with minimal config, regardless of their profile name. Either enable `catppuccin.<browser>.enable` or `catppuccin.enable`, and install Firefox Color
=> feat(home-manager/firefox): use options submodule to apply configuration

CHANGELOG.md, README.md
This were missed in https://github.com/catppuccin/nix/pull/627 and https://github.com/catppuccin/nix/pull/655
=> docs(README): update website links

modules/home-manager/halloy.nix, modules/tests/home.nix, pkgs/sources.json
closes https://github.com/catppuccin/nix/issues/568
=> feat(home-manager/halloy): init

modules/home-manager/all-modules.nix
perhaps the skill issue of all time
=> fix(home-manager): import halloy
